### PR TITLE
Add contributor list

### PR DESCRIPTION
**Pull request by wu-sheng**
@clevertension @IluckySi @lytscu @mircoteam @neeuq @TastySummer @wendal @zhangkewei @xcaspar @chidaodezhongsheng

### CODE REVIEW

**Comment by wu-sheng** [comment]
@clevertension @IluckySi @lytscu @mircoteam @neeuq @TastySummer @wendal @zhangkewei @xcaspar @chidaodezhongsheng 
You are all recorded as GitHub contributors. I start to maintain the contributors list in this org repo.

You can send a pull request to `contrib-list` branch, for updating your Chinese name, company, job-title, etc. I will keep this pr in more than 7 days for your guys. After that, you can sent the pull request to `master` branch.

**Comment by wu-sheng** [comment]
FYI @OpenSkywalking/pmc @OpenSkywalking/committer-team @OpenSkywalking/huawei-devcloud-contributor-team

**Comment by chidaodezhongsheng** [comment]
Github：chidaodezhongsheng
Name：林嘉琦
Company：当当
Job-title：架构部研发工程师

技术部·架构部·林嘉琦
手机：18710075837
Email：linjiaqi@dangdang.com<mailto:linjiaqi@dangdang.com>
QQ：928926755

发件人: 吴晟 Wu Sheng [mailto:notifications@github.com]
发送时间: 2017年11月1日 17:44
收件人: OpenSkywalking/Organization
抄送: 林嘉琦; Mention
主题: Re: [OpenSkywalking/Organization] Add contributor list (#1)


FYI @OpenSkywalking/pmc<https://github.com/orgs/OpenSkywalking/teams/pmc> @OpenSkywalking/committer-team<https://github.com/orgs/OpenSkywalking/teams/committer-team> @OpenSkywalking/huawei-devcloud-contributor-team<https://github.com/orgs/OpenSkywalking/teams/huawei-devcloud-contributor-team>

**Comment by wu-sheng** [comment]
@zuohl chech here.

**Pull request merged**
